fix(isPartof schema): Duplicate productID issue
quintype/quintype-node-seo pull request #330
Opened 2020-11-26 10:57 UTC by shraddha-kesari

# Description

Structured data tool is throwing error for duplicate productID property in isPartOf schema.
productID is added to isPartOf schema for amp subscriptions. Which is added to NewsArticle and Article schema. It should only be part of NewsArticle Schema. 

Fixes # (issue-reference)
Removed productID from isPartOf schema which is a part of Article schema. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Open an amp story of a publisher which uses amp library. Check for the error on Structured data tool. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-02 09:11 UTC, sanju296 commented
**Ticket:** https://github.com/quintype/quintype-amp/issues/307
**Test Cases executed for testing the structured data:**

- [ ] Verify that the productID is shown only in News Article and not in the article schema. - PASS

- [ ] Adding the subscriptions object and the isAmpSubscriptionsEnabled:true. PASS
Expected Result: The productID must be visible in the structured data and the paywall must be shown on the FE.

- [ ] Adding the Subscriptions object but not the isAmpSubscriptionsEnabled:true. PASS
Expected Result: The productID must not be visible in the structured data.

- [ ] Adding the Subscriptions object but keeping the isAmpSubscriptionsEnabled:false. PASS
Expected Result: The productID must not be visible in the structured data.

- [ ] Not adding the Subscriptions object but adding isAmpSubscriptionsEnabled:true. PASS
Expected Result: The productID must be visible in the structured data.

- [ ] Not adding the Subscriptions object but adding isAmpSubscriptionsEnabled:false. PASS
Expected Result: The productID must not be visible in the structured data.

2020-12-03 07:55 UTC, ags1773 requested changes

2020-12-03 07:55 UTC, ags1773 commented on src/structured-data/structured-data-tags.js
> +      isPartOf: generateIsPartOfDataForNewArticle(story, publisherConfig, pageType, structuredData),
function name should be `generateIsPartOfDataForNewsArticle `

2020-12-03 07:55 UTC, ags1773 commented on src/structured-data/structured-data-tags.js
You can make function `generateIsPartOfDataForNewArticle` DRYer by doing this

```js
function generateIsPartOfDataForNewArticle(story ={}, publisherConfig = {}, pageType = '', structuredData = {}) {
  const publisherName = publisherConfig['publisher-name'];
  const productId = publisherConfig['publisher-name'] + '.com:basic';
  const isPartOfData = generateIsPartOfDataForArticle(story, publisherConfig, pageType);

  if(pageType === 'story-page-amp' && structuredData.isAmpSubscriptionsEnabled) {
    return Object.assign(
      {},
      {
        '@type': ['WebPage', 'CreativeWork', 'Product'],
        name: publisherName,
        productID: productId,
        url: `${publisherConfig['sketches-host']}/${story.slug}`,
        primaryImageOfPage: generateArticleImageData(
          story['hero-image-s3-key'],
          publisherConfig,
          pageType
        ),
      }
    )
  }
  return isPartOfData
}
```

2020-12-04 06:12 UTC, ags1773 approved these changes

2020-12-07 10:43 UTC, merged